/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ewaste.ui.accountant;

import com.ewaste.business.enterprise.Enterprise;
import com.ewaste.business.network.Network;
import com.ewaste.business.order.OrderItem;
import com.ewaste.business.organization.Organization;
import com.ewaste.business.organization.ReceiverOrganization;
import com.ewaste.business.organization.UserOrganization;
import com.ewaste.business.useraccount.UserAccount;
import com.ewaste.business.workqueue.WorkRequest;
import com.ewaste.business.helper.MyComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jyotsna Khatter
 */
public class AccountantReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountantReportsPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ReceiverOrganization organization;
    private Enterprise enterprise;
    private Network network;
    double totalrevenue = 0;
    int totalProductSold = 0;
    double totalRevenueFromRecycledProducts = 0;
    double totalRevenueFromUsedProducts = 0;
    
    public AccountantReportsPanel(JPanel userProcessContainer, UserAccount userAccount, Network network, Enterprise enterprise, ReceiverOrganization organization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        calculateTotalRevenue();
        calculateRevenueFromRecycledPrd();
    }

    private void calculateTotalRevenue(){
        
        
        //profit from selling recycled products to manufacturer
        for(WorkRequest wr: organization.getWorkQueue().getWorkRequestList()){
            totalrevenue += wr.getProduct().getSellingPrice();
        }
        
        totalRevenueFromRecycledProducts = totalrevenue;
        lblsellRecycleprd.setText(String.valueOf(totalrevenue));
        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof UserOrganization){
                //buying products from user
                for(WorkRequest wr: o.getWorkQueue().getWorkRequestList()){
                    totalrevenue -= wr.getProduct().getSellingPrice();
                }
                //selling used products to user
                for(UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                    for(OrderItem oi :ua.getOrderList().getOrderItemList()){
                        totalrevenue += oi.getProduct().getSellingPrice();
                        totalProductSold++;
                    }
                }
            }
        }
        
        lblProductSold.setText(String.valueOf(totalProductSold));
        lblTotalRevenue.setText(String.valueOf(totalrevenue));
    }
    
    
    public void calculateRevenueFromRecycledPrd(){        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof UserOrganization){
                //selling used products to user
                for(UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                    for(OrderItem oi :ua.getOrderList().getOrderItemList()){
                        totalRevenueFromUsedProducts += oi.getProduct().getSellingPrice();
                    }
                }
            }
        lblSellingPrd.setText(String.valueOf(totalrevenue));
        }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JTextField();
        lblProductSold = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSellingPrd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblsellRecycleprd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("TOTAL REVENUE COLLECTED : ");

        jLabel2.setText("NUMBER OF PRODUCTS SOLD :");

        lblProductSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProductSoldActionPerformed(evt);
            }
        });

        jButton1.setText("< BACK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Accountant Department");

        jLabel4.setText("REVENUE FROM SELLING USED PRODUCT:");

        lblSellingPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSellingPrdActionPerformed(evt);
            }
        });

        jLabel5.setText("REVENUE FROM SELLING RECYCLED PRODUCTS");

        lblsellRecycleprd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblsellRecycleprdActionPerformed(evt);
            }
        });

        jButton2.setText("View Graphical Rpresentation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(lblProductSold)
                                            .addComponent(lblSellingPrd)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(lblsellRecycleprd)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblProductSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblSellingPrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblsellRecycleprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblProductSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProductSoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductSoldActionPerformed

    private void lblSellingPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSellingPrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSellingPrdActionPerformed

    private void lblsellRecycleprdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblsellRecycleprdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblsellRecycleprdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.getContentPane().add(new MyComponent((int)totalRevenueFromRecycledProducts,(int)totalRevenueFromUsedProducts,0,0));
        frame.setSize(300, 200);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lblProductSold;
    private javax.swing.JTextField lblSellingPrd;
    private javax.swing.JTextField lblTotalRevenue;
    private javax.swing.JTextField lblsellRecycleprd;
    // End of variables declaration//GEN-END:variables
}
