/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ewaste.ui.userworkarea;

import com.ewaste.business.enterprise.Enterprise;
import com.ewaste.business.helper.Constant;
import com.ewaste.business.helper.Parser;
import com.ewaste.business.helper.Util;
import com.ewaste.business.network.Network;
import com.ewaste.business.organization.Organization;
import com.ewaste.business.organization.SortingOrganization;
import com.ewaste.business.product.Category;
import com.ewaste.business.product.Product;
import com.ewaste.business.useraccount.UserAccount;
import com.ewaste.business.workqueue.DismantleWorkRequest;
import com.ewaste.business.workqueue.SortingWorkRequest;
import com.ewaste.business.workqueue.TesterWorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jyotsna Khatter
 */
public class SellEWastePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private String path;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Network network;

    JFileChooser fileChooser;
    File csvFile = null;

    /**
     * Creates new form SellEWastePanel
     */
    public SellEWastePanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.enterprise = enterprise;
    }

    public String[] getComponent(String componentType) {

        String[] component = new String[5];
        if (componentType.equalsIgnoreCase("Large household appliances")) {
            component[0] = "Ovens";
            component[1] = "Refrigetors";
            component[2] = "Washer";
            component[3] = "Dryer";

        }

        if (componentType.equalsIgnoreCase("Small household appliances")) {
            component[0] = "Blenders";
            component[1] = "Fans";
            component[2] = "Vaccum";
            component[3] = "Microwaves";
        }

        if (componentType.equalsIgnoreCase("Computer parts")) {
            component[0] = "Boards";
            component[1] = "Disc Drives";
            component[2] = "Hard drives";
            component[3] = "Power supplies";
        }

        if (componentType.equalsIgnoreCase("Industry System")) {
            component[0] = "Desktop";
            component[1] = "Laptop";
            component[2] = "Servers";
            component[3] = "Large Office Printers";
            component[4] = "Power Supplies";
        }
        if (componentType.equalsIgnoreCase("Networking Equipment")) {
            component[0] = "Routers";
            component[1] = "Modems";
            component[2] = "SwitchBoards";
            component[3] = "CRT";
            component[4] = "Alkaline Batteries";
        }
        return component;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelSell = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnbrowse = new javax.swing.JButton();
        btnAttach = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtFeatures = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSellingPrice = new javax.swing.JTextField();
        cmbDateChooser = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblComponentType = new javax.swing.JLabel();
        cmbComponentType = new javax.swing.JComboBox<>();
        txtPath = new javax.swing.JTextField();
        lblProductImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblCSVName = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        jLabel1.setText("SELL YOUR PRODUCT");

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Name");

        jLabel4.setText("Category:");

        jLabel5.setText("Quantity:");

        jLabel6.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel7.setText("Upload Picture:");

        btnbrowse.setText("Browse");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        jButton4.setText("< BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Features");

        jLabel10.setText("Selling Price");

        jLabel11.setText("Manufacture/Purchase Date");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product Category", "Large household appliances", "Small household appliances", "Computer parts", "Industry System", "Networking Equipment" }));
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        lblComponentType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblComponentType.setText("Component Type");

        cmbComponentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbComponentTypeItemStateChanged(evt);
            }
        });
        cmbComponentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComponentTypeActionPerformed(evt);
            }
        });

        lblProductImg.setMaximumSize(new java.awt.Dimension(300, 300));
        lblProductImg.setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout PanelSellLayout = new javax.swing.GroupLayout(PanelSell);
        PanelSell.setLayout(PanelSellLayout);
        PanelSellLayout.setHorizontalGroup(
            PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSellLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSellLayout.createSequentialGroup()
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelSellLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSellLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(109, 109, 109))
                            .addGroup(PanelSellLayout.createSequentialGroup()
                                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComponentType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelSellLayout.createSequentialGroup()
                                        .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel10)
                                                .addGroup(PanelSellLayout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnbrowse))
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)))
                                        .addGap(0, 35, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategory, 0, 475, Short.MAX_VALUE)
                                    .addGroup(PanelSellLayout.createSequentialGroup()
                                        .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbComponentType, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtSellingPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtManufacturer, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFeatures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelSellLayout.createSequentialGroup()
                                                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(PanelSellLayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(64, 64, 64)
                                                .addComponent(lblProductImg, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 41, Short.MAX_VALUE))))))
                    .addGroup(PanelSellLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGap(107, 107, 107))
        );
        PanelSellLayout.setVerticalGroup(
            PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSellLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbComponentType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComponentType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSellLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelSellLayout.createSequentialGroup()
                        .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSellLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(47, 47, 47)
                                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(btnbrowse)
                                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAttach)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSellLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblProductImg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(PanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Sell Individual Product", PanelSell);

        jLabel12.setText("Upload CSV file");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpload)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addGap(40, 40, 40)
                        .addComponent(lblCSVName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(lblCSVName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnUpload)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sell Multiple products", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(PanelSell);
        File f = fc.getSelectedFile();
        path = f.getAbsolutePath();
        txtPath.setText(path);
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        boolean valid = true;
        String manufacturer = txtManufacturer.getText();
        String productName = txtName.getText();
        String sellingPrice = txtSellingPrice.getText();
        String quantity = spnQuantity.getValue().toString();
        String features = txtFeatures.getText();
        String desc = txtDescription.getText();

        String[] attr = new String[4];

        attr[0] = manufacturer;
        attr[1] = productName;
        attr[2] = features;
        attr[3] = desc;

        for (String val : attr) {
            if (val == "null" || val.isEmpty() || val.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kindly enter information marked with * before submitting", null, JOptionPane.WARNING_MESSAGE);
                valid = false;
                break;
            }
        }

        if (valid) {

            Product product = new Product();
            product.setProductManufacturer(manufacturer);
            product.setProductName(productName);
            if (!quantity.equals("0")) {
                product.setSellingPrice(Double.parseDouble(sellingPrice));
            } else {
                product.setSellingPrice(0);
            }

            if (!quantity.equals("0")) {
                product.setQuantity(Double.parseDouble(quantity));
            } else {
                product.setQuantity(0);
            }

            product.setCategory((String)cmbCategory.getSelectedItem());
            String strDate = cmbDateChooser.getText();
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date manufacturingDate = null;
            try {
                manufacturingDate = df.parse(strDate);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            product.setDateOfManufacturer(manufacturingDate);

            SortingWorkRequest request = new SortingWorkRequest();
            request.setProduct(product);
            request.setSender(userAccount);
            request.setStatus(Constant.SENT_TO_SORTER);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof SortingOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            JOptionPane.showMessageDialog(this, "Product requested to be recycled. \n We would get back to you once it is approved.");
            resetFields();
        }
    }//GEN-LAST:event_btnSellActionPerformed

    private void resetFields() {
        txtDescription.setText("");
        txtFeatures.setText("");
        txtSellingPrice.setText("");
        txtName.setText("");
        txtManufacturer.setText("");
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:

        try {
            fileChooser = new JFileChooser();
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                csvFile = fileChooser.getSelectedFile();
                if (csvFile.getName().endsWith(".csv")
                        || csvFile.getName().endsWith(".CSV")) {
                    lblCSVName.setText(csvFile.getName());
                } else {
                    JOptionPane.showMessageDialog(null, "Only .csv file allowed");
                    csvFile = null;
                    lblCSVName.setText(null);
                }
            } else {
                csvFile = null;
            }
        } catch (Exception exception) {
            exception.printStackTrace();
        }

    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:

        if (csvFile == null) {
            JOptionPane.showMessageDialog(this, "Please select a file");
            return;
        } else {
            String line = "";
            Properties props = new Properties();
            BufferedReader br = null;
            Parser parser = new Parser();
            try {
                br = new BufferedReader(new FileReader(csvFile));
                br.readLine();
                while ((line = br.readLine()) != null) {
                    props = parser.parseRow(line);
                    if (props.isEmpty()) {
                        continue;
                    }
                    populateVo(props);

                }
                JOptionPane.showMessageDialog(this, "Product requested to be recycled. \n We would get back to you once it is approved.");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (br != null) {
                    try {
                        br.close();
                    } catch (IOException e) {
                        e.printStackTrace();

                    }
                }
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.cmbCategory.getSelectedIndex() > 0) {
                this.cmbComponentType.setModel(new DefaultComboBoxModel(this.getComponent(this.cmbCategory.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void cmbComponentTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbComponentTypeItemStateChanged

    }//GEN-LAST:event_cmbComponentTypeItemStateChanged

    private void cmbComponentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComponentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbComponentTypeActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        ImageIcon setImg = new ImageIcon(path);
        Image img = setImg.getImage();
        Image resize = img.getScaledInstance(250, 250, Image.SCALE_SMOOTH);

        Icon icon = new ImageIcon(resize);

        lblProductImg.setIcon(icon);

        lblProductImg.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_btnAttachActionPerformed

    private void populateVo(Properties props) {
        Product product = new Product();
        product.setProductName(props.get("productName").toString());
        product.setProductManufacturer(props.get("productManufacturer").toString());
        product.setProducDescription(props.get("producDescription").toString());
        product.setProductFeatures(props.get("productFeatures").toString());
        product.setSellingPrice(Double.valueOf(props.get("sellingPrice").toString()));
        //productVo.setCategory(props.getProperty("category").);
        product.setDateOfManufacturer(Util.getDate(props.get("dateOfManufacturer").toString()));
        product.setQuantity(Double.valueOf(props.get("quantity").toString()));
        System.out.println(product);

        SortingWorkRequest request = new SortingWorkRequest();
        request.setProduct(product);
        request.setSender(userAccount);
        request.setStatus(Constant.SENT_TO_SORTER);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof SortingOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSell;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnbrowse;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbComponentType;
    private datechooser.beans.DateChooserCombo cmbDateChooser;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCSVName;
    private javax.swing.JLabel lblComponentType;
    private javax.swing.JLabel lblProductImg;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtFeatures;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
