/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ewaste.ui.userworkarea;

import com.ewaste.business.EcoSystem;
import com.ewaste.business.enterprise.Enterprise;
import com.ewaste.business.network.Network;
import com.ewaste.business.organization.Organization;
import com.ewaste.business.organization.UserOrganization;
import com.ewaste.business.useraccount.UserAccount;
import com.ewaste.ui.systemadminworkarea.ManageNetworkJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author varsha bhanushali
 */
public class UserWorkAreaPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private UserOrganization organization;
    private Enterprise enterprise;
    private Network network;
    /**
     * Creates new form UserWorkAreaPanel
     * @param userProcessContainer
     * @param userAccount
     * @param organization
     */
    public UserWorkAreaPanel(JPanel userProcessContainer, UserAccount userAccount, UserOrganization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        btnBuyEWaste = new javax.swing.JButton();
        btnSellEwaste = new javax.swing.JButton();
        btnDonateEWaste = new javax.swing.JButton();
        btnManageOrganzation = new javax.swing.JButton();

        lblHeader.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblHeader.setText("Welcome User");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(88, 233, 162));
        label2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 0));
        label2.setText(" Re-Think Re-Cycle");

        btnBuyEWaste.setText("Buy E-waste");
        btnBuyEWaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyEWasteActionPerformed(evt);
            }
        });

        btnSellEwaste.setText("Sell E-waste");
        btnSellEwaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellEwasteActionPerformed(evt);
            }
        });

        btnDonateEWaste.setText("Donate E-waste ");
        btnDonateEWaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateEWasteActionPerformed(evt);
            }
        });

        btnManageOrganzation.setText("Manage Orders");
        btnManageOrganzation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganzationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSellEwaste, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuyEWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDonateEWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageOrganzation, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnManageOrganzation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuyEWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSellEwaste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDonateEWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyEWasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyEWasteActionPerformed
        // TODO add your handling code here:
        BuyEwastePanel buyEwasteJPanel = new BuyEwastePanel(userProcessContainer, userAccount, network);
        userProcessContainer.add("BuyEwastePanel", buyEwasteJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyEWasteActionPerformed

    private void btnSellEwasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellEwasteActionPerformed
        // TODO add your handling code here:
        SellEWastePanel sellEwasteJPanel = new SellEWastePanel(userProcessContainer, userAccount, organization, enterprise, network);
        userProcessContainer.add("BuyEwastePanel", sellEwasteJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellEwasteActionPerformed

    private void btnDonateEWasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateEWasteActionPerformed
        // TODO add your handling code here:
        DonateEWastePanel donateEwasteJPanel = new DonateEWastePanel(userProcessContainer, userAccount, network);
        userProcessContainer.add("BuyEwastePanel", donateEwasteJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonateEWasteActionPerformed

    private void btnManageOrganzationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganzationActionPerformed
        // TODO add your handling code here:
        ManageOrdersPanel manageOrdersPanel = new ManageOrdersPanel(userProcessContainer, userAccount, organization, enterprise, network);
        userProcessContainer.add("ManageOrdersPanel", manageOrdersPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganzationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyEWaste;
    private javax.swing.JButton btnDonateEWaste;
    private javax.swing.JButton btnManageOrganzation;
    private javax.swing.JButton btnSellEwaste;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label2;
    private java.awt.Label lblHeader;
    // End of variables declaration//GEN-END:variables
}
