/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ewaste.ui.testingWorkArea;

import com.ewaste.business.enterprise.Enterprise;
import com.ewaste.business.enterprise.OtherRecyclerEnterprise;
import com.ewaste.business.helper.Constant;
import com.ewaste.business.network.Network;
import com.ewaste.business.organization.DismantleOrganization;
import com.ewaste.business.organization.DisposalOrganization;
import com.ewaste.business.organization.ExtractionOrganization;
import com.ewaste.business.organization.Organization;
import com.ewaste.business.organization.ReceiverOrganization;
import com.ewaste.business.organization.SortingOrganization;
import com.ewaste.business.organization.TestingOrganization;
import com.ewaste.business.product.Product;
import com.ewaste.business.useraccount.UserAccount;
import com.ewaste.business.workqueue.DisposalWorkRequest;
import com.ewaste.business.workqueue.SortingWorkRequest;
import com.ewaste.business.workqueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author varsha bhanushali
 */
public class ProductTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductTestPanel
     */
    
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private TestingOrganization testingOrganization;
    private WorkRequest workRequest;
    private Enterprise enterprise;
    private Network network;
    
    public ProductTestPanel(JPanel userProcessContainer, UserAccount userAccount, WorkRequest workRequest, TestingOrganization testingOrganization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount=userAccount;
        this.testingOrganization = testingOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.workRequest = workRequest;
        populateData();
    }
    
    private void populateData(){
        txtComponentName.setText(workRequest.getProduct().getProductName()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        functionalButtonGroup = new javax.swing.ButtonGroup();
        physicalButtonGroup = new javax.swing.ButtonGroup();
        internaButtonGroup = new javax.swing.ButtonGroup();
        usedEarlierButtonGroup = new javax.swing.ButtonGroup();
        bgAge = new javax.swing.ButtonGroup();
        bgEnergyUse = new javax.swing.ButtonGroup();
        bgCorrosion = new javax.swing.ButtonGroup();
        bgCapacitance = new javax.swing.ButtonGroup();
        bgPower = new javax.swing.ButtonGroup();
        bgAcceptance = new javax.swing.ButtonGroup();
        bgQuality = new javax.swing.ButtonGroup();
        bgProtection = new javax.swing.ButtonGroup();
        bgPerformance = new javax.swing.ButtonGroup();
        bgEnergy = new javax.swing.ButtonGroup();
        bgToxic = new javax.swing.ButtonGroup();
        bgLead = new javax.swing.ButtonGroup();
        bgExtraction = new javax.swing.ButtonGroup();
        bgPrecious = new javax.swing.ButtonGroup();
        bgMetals = new javax.swing.JTabbedPane();
        ageButtonGroup = new javax.swing.JPanel();
        lblFunctional = new javax.swing.JLabel();
        rdFunctionalYes = new javax.swing.JRadioButton();
        rdFunctionalNo = new javax.swing.JRadioButton();
        lblPhysicalYes = new javax.swing.JLabel();
        rdPhysicalYes = new javax.swing.JRadioButton();
        rdPhysicalNo = new javax.swing.JRadioButton();
        lblInternalDamage = new javax.swing.JLabel();
        rdXYes = new javax.swing.JRadioButton();
        rdXNo = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rdReYes = new javax.swing.JRadioButton();
        rdReNo = new javax.swing.JRadioButton();
        lblAge = new javax.swing.JLabel();
        rdAgeYes = new javax.swing.JRadioButton();
        rdAgeNo = new javax.swing.JRadioButton();
        submitPhysicalButton = new javax.swing.JButton();
        lblPhysicalYes1 = new javax.swing.JLabel();
        rdlowCorrosion = new javax.swing.JRadioButton();
        rdHighCorrosion = new javax.swing.JRadioButton();
        rdVHighCorrosion = new javax.swing.JRadioButton();
        lblPhysicalYes2 = new javax.swing.JLabel();
        rdlowCorrosion1 = new javax.swing.JRadioButton();
        rdHighCorrosion1 = new javax.swing.JRadioButton();
        rdVHighCorrosion1 = new javax.swing.JRadioButton();
        rdProtectFail = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        submitComponentButton = new javax.swing.JButton();
        rdAccPass = new javax.swing.JRadioButton();
        rdAccFail = new javax.swing.JRadioButton();
        rdQualityPass = new javax.swing.JRadioButton();
        rdQualityFail = new javax.swing.JRadioButton();
        rdProtectPass = new javax.swing.JRadioButton();
        rdProFail = new javax.swing.JRadioButton();
        rdPerformPass = new javax.swing.JRadioButton();
        rdPerformFail = new javax.swing.JRadioButton();
        rdLowPower = new javax.swing.JRadioButton();
        rdPowerHigh = new javax.swing.JRadioButton();
        rdRange = new javax.swing.JRadioButton();
        rdOutRange = new javax.swing.JRadioButton();
        rdPowerVHigh = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        rdToxicLow = new javax.swing.JRadioButton();
        rdToxicHigh = new javax.swing.JRadioButton();
        rdToxicVHigh = new javax.swing.JRadioButton();
        rdEnergyLow = new javax.swing.JRadioButton();
        rdEnergyHigh = new javax.swing.JRadioButton();
        rdEnergyVHigh = new javax.swing.JRadioButton();
        rdExtractEase = new javax.swing.JRadioButton();
        rdExtractVhard = new javax.swing.JRadioButton();
        rdExtractHard = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        rdLeadLow = new javax.swing.JRadioButton();
        rdLeadHigh = new javax.swing.JRadioButton();
        rdLeadVHigh = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbAction = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblComponentName = new javax.swing.JLabel();
        txtComponentName = new javax.swing.JTextField();

        bgMetals.setBackground(new java.awt.Color(204, 255, 255));
        bgMetals.setEnabled(false);

        lblFunctional.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFunctional.setText("Functional :");

        functionalButtonGroup.add(rdFunctionalYes);
        rdFunctionalYes.setText("Yes");
        rdFunctionalYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFunctionalYesActionPerformed(evt);
            }
        });

        functionalButtonGroup.add(rdFunctionalNo);
        rdFunctionalNo.setText("No");

        lblPhysicalYes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPhysicalYes.setText("Physical damage : ");

        physicalButtonGroup.add(rdPhysicalYes);
        rdPhysicalYes.setText("Yes");
        rdPhysicalYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPhysicalYesActionPerformed(evt);
            }
        });

        physicalButtonGroup.add(rdPhysicalNo);
        rdPhysicalNo.setText("No");

        lblInternalDamage.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblInternalDamage.setText("Internal damage (x-ray): ");

        internaButtonGroup.add(rdXYes);
        rdXYes.setText("Yes");

        internaButtonGroup.add(rdXNo);
        rdXNo.setText("No");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("Is it reused earlier ?");

        usedEarlierButtonGroup.add(rdReYes);
        rdReYes.setText("Yes");

        usedEarlierButtonGroup.add(rdReNo);
        rdReNo.setText("No");

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAge.setText("Age of component :");

        bgAge.add(rdAgeYes);
        rdAgeYes.setText("0 - 5 yrs");

        bgAge.add(rdAgeNo);
        rdAgeNo.setText("5+ years");

        submitPhysicalButton.setText("Next >");
        submitPhysicalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPhysicalButtonActionPerformed(evt);
            }
        });

        lblPhysicalYes1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPhysicalYes1.setText("Level of corrosion :");

        bgCorrosion.add(rdlowCorrosion);
        rdlowCorrosion.setText("low");

        bgCorrosion.add(rdHighCorrosion);
        rdHighCorrosion.setText("high");

        bgCorrosion.add(rdVHighCorrosion);
        rdVHighCorrosion.setText("very high");

        lblPhysicalYes2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPhysicalYes2.setText("Presence of precious metals :");

        bgPrecious.add(rdlowCorrosion1);
        rdlowCorrosion1.setText("low");

        bgPrecious.add(rdHighCorrosion1);
        rdHighCorrosion1.setText("high");
        rdHighCorrosion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHighCorrosion1ActionPerformed(evt);
            }
        });

        bgPrecious.add(rdVHighCorrosion1);
        rdVHighCorrosion1.setText("very high");

        javax.swing.GroupLayout ageButtonGroupLayout = new javax.swing.GroupLayout(ageButtonGroup);
        ageButtonGroup.setLayout(ageButtonGroupLayout);
        ageButtonGroupLayout.setHorizontalGroup(
            ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ageButtonGroupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitPhysicalButton)
                .addGap(70, 70, 70))
            .addGroup(ageButtonGroupLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhysicalYes1)
                    .addGroup(ageButtonGroupLayout.createSequentialGroup()
                        .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ageButtonGroupLayout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addGap(64, 64, 64)))
                            .addGroup(ageButtonGroupLayout.createSequentialGroup()
                                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFunctional, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhysicalYes)
                                    .addComponent(lblInternalDamage))
                                .addGap(54, 54, 54)))
                        .addGap(43, 43, 43)
                        .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdAgeYes)
                            .addComponent(rdlowCorrosion)
                            .addComponent(rdReYes)
                            .addComponent(rdXYes)
                            .addComponent(rdPhysicalYes)
                            .addComponent(rdFunctionalYes)
                            .addComponent(rdlowCorrosion1))
                        .addGap(18, 18, 18)
                        .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdFunctionalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdPhysicalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdXNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdReNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdHighCorrosion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdAgeNo)
                            .addComponent(rdHighCorrosion1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPhysicalYes2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdVHighCorrosion)
                    .addComponent(rdVHighCorrosion1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        ageButtonGroupLayout.setVerticalGroup(
            ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ageButtonGroupLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFunctional)
                    .addComponent(rdFunctionalYes)
                    .addComponent(rdFunctionalNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhysicalYes)
                    .addComponent(rdPhysicalYes)
                    .addComponent(rdPhysicalNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInternalDamage)
                    .addComponent(rdXYes)
                    .addComponent(rdXNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rdReYes)
                    .addComponent(rdReNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(rdAgeYes)
                    .addComponent(rdAgeNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdHighCorrosion)
                    .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhysicalYes1)
                        .addComponent(rdlowCorrosion)
                        .addComponent(rdVHighCorrosion)))
                .addGap(12, 12, 12)
                .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ageButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdHighCorrosion1)
                        .addComponent(rdVHighCorrosion1))
                    .addComponent(rdlowCorrosion1)
                    .addComponent(lblPhysicalYes2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(submitPhysicalButton)
                .addGap(44, 44, 44))
        );

        bgMetals.addTab("Physical properties", ageButtonGroup);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Capacitance, Resistance :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel19.setText("Power utilization  :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setText("Acceptance Testing :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setText("Quality  Testing :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Performance Testing :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setText("Protection mechnism : ");

        submitComponentButton.setText("Next >");
        submitComponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitComponentButtonActionPerformed(evt);
            }
        });

        bgAcceptance.add(rdAccPass);
        rdAccPass.setText("Pass ");

        bgAcceptance.add(rdAccFail);
        rdAccFail.setText("Fail");
        rdAccFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAccFailActionPerformed(evt);
            }
        });

        bgQuality.add(rdQualityPass);
        rdQualityPass.setText("Pass ");

        bgQuality.add(rdQualityFail);
        rdQualityFail.setText("Fail");
        rdQualityFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdQualityFailActionPerformed(evt);
            }
        });

        bgProtection.add(rdProtectPass);
        rdProtectPass.setText("Pass ");
        rdProtectPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdProtectPassActionPerformed(evt);
            }
        });

        bgProtection.add(rdProFail);
        rdProFail.setText("Fail");
        rdProFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdProFailActionPerformed(evt);
            }
        });

        bgPerformance.add(rdPerformPass);
        rdPerformPass.setText("Pass ");

        bgPerformance.add(rdPerformFail);
        rdPerformFail.setText("Fail");
        rdPerformFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPerformFailActionPerformed(evt);
            }
        });

        bgPower.add(rdLowPower);
        rdLowPower.setText("Low");
        rdLowPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLowPowerActionPerformed(evt);
            }
        });

        bgPower.add(rdPowerHigh);
        rdPowerHigh.setText("high");
        rdPowerHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPowerHighActionPerformed(evt);
            }
        });

        bgCapacitance.add(rdRange);
        rdRange.setText("In Range");
        rdRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRangeActionPerformed(evt);
            }
        });

        bgCapacitance.add(rdOutRange);
        rdOutRange.setText("Outside Range");
        rdOutRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOutRangeActionPerformed(evt);
            }
        });

        bgPower.add(rdPowerVHigh);
        rdPowerVHigh.setText("very high");
        rdPowerVHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPowerVHighActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rdProtectFailLayout = new javax.swing.GroupLayout(rdProtectFail);
        rdProtectFail.setLayout(rdProtectFailLayout);
        rdProtectFailLayout.setHorizontalGroup(
            rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdProtectFailLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdRange)
                        .addGap(25, 25, 25)
                        .addComponent(rdOutRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                        .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rdProtectFailLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdPerformPass)
                                .addGap(51, 51, 51)
                                .addComponent(rdPerformFail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rdProtectFailLayout.createSequentialGroup()
                                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                                        .addComponent(rdLowPower)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdPowerHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                                        .addComponent(rdQualityPass)
                                        .addGap(51, 51, 51)
                                        .addComponent(rdQualityFail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                                        .addComponent(rdAccPass)
                                        .addGap(51, 51, 51)
                                        .addComponent(rdAccFail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                                        .addComponent(rdProtectPass)
                                        .addGap(51, 51, 51)
                                        .addComponent(rdProFail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(rdPowerVHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rdProtectFailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitComponentButton)
                .addGap(132, 132, 132))
        );
        rdProtectFailLayout.setVerticalGroup(
            rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdProtectFailLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rdOutRange)
                    .addComponent(rdRange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rdLowPower)
                    .addComponent(rdPowerHigh)
                    .addComponent(rdPowerVHigh))
                .addGap(22, 22, 22)
                .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rdProtectFailLayout.createSequentialGroup()
                        .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(rdAccPass)
                            .addComponent(rdAccFail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(rdQualityPass)
                            .addComponent(rdQualityFail))
                        .addGap(18, 18, 18)
                        .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(rdProtectPass)
                            .addComponent(rdProFail))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addGroup(rdProtectFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdPerformPass)
                        .addComponent(rdPerformFail)))
                .addGap(31, 31, 31)
                .addComponent(submitComponentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgMetals.addTab("component testing", rdProtectFail);

        jPanel4.setFocusTraversalPolicyProvider(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Energy use :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Levels of toxic chemicals : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Lifespan : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Ease of Extraction : ");

        calcButton.setText("Calculate ");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        bgToxic.add(rdToxicLow);
        rdToxicLow.setText("Low");
        rdToxicLow.setFocusTraversalPolicyProvider(true);
        rdToxicLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdToxicLowActionPerformed(evt);
            }
        });

        bgToxic.add(rdToxicHigh);
        rdToxicHigh.setText("high");
        rdToxicHigh.setFocusTraversalPolicyProvider(true);

        bgToxic.add(rdToxicVHigh);
        rdToxicVHigh.setText("very High");
        rdToxicVHigh.setFocusTraversalPolicyProvider(true);

        bgEnergy.add(rdEnergyLow);
        rdEnergyLow.setText("Low");
        rdEnergyLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEnergyLowActionPerformed(evt);
            }
        });

        bgEnergy.add(rdEnergyHigh);
        rdEnergyHigh.setText("high");

        bgEnergy.add(rdEnergyVHigh);
        rdEnergyVHigh.setText("very High");

        bgExtraction.add(rdExtractEase);
        rdExtractEase.setText("very easy");
        rdExtractEase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdExtractEaseActionPerformed(evt);
            }
        });

        bgExtraction.add(rdExtractVhard);
        rdExtractVhard.setText("very hard");
        rdExtractVhard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdExtractVhardActionPerformed(evt);
            }
        });

        bgExtraction.add(rdExtractHard);
        rdExtractHard.setText("hard");
        rdExtractHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdExtractHardActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Lead Content : ");

        bgLead.add(rdLeadLow);
        rdLeadLow.setText("Low");
        rdLeadLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLeadLowActionPerformed(evt);
            }
        });

        bgLead.add(rdLeadHigh);
        rdLeadHigh.setText("high");
        rdLeadHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLeadHighActionPerformed(evt);
            }
        });

        bgLead.add(rdLeadVHigh);
        rdLeadVHigh.setText("very High");

        jLabel2.setText("Action");

        cmbAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Working Fine", "Send to Disposal", "Send for Extraction", "Send to third party for recycling" }));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rdToxicLow)
                                            .addComponent(rdEnergyLow, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(16, 16, 16)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rdEnergyHigh)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdEnergyVHigh))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(rdToxicHigh)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdToxicVHigh))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSubmit)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdExtractEase)
                                            .addComponent(rdLeadLow))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rdExtractHard)
                                                .addGap(8, 8, 8)
                                                .addComponent(rdExtractVhard))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rdLeadHigh)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdLeadVHigh))))))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(calcButton)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cmbAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdEnergyLow)
                    .addComponent(rdEnergyHigh)
                    .addComponent(rdEnergyVHigh))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdToxicLow)
                    .addComponent(rdToxicHigh)
                    .addComponent(rdToxicVHigh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdExtractEase)
                    .addComponent(rdExtractHard)
                    .addComponent(rdExtractVhard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdLeadHigh)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(rdLeadLow)
                        .addComponent(rdLeadVHigh)))
                .addGap(37, 37, 37)
                .addComponent(calcButton)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        bgMetals.addTab("Environmental parameters", jPanel4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Testing Department");

        lblComponentName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblComponentName.setText("Component Name : ");

        txtComponentName.setEnabled(false);
        txtComponentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComponentNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblComponentName)
                .addGap(57, 57, 57)
                .addComponent(txtComponentName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponentName)
                    .addComponent(txtComponentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(bgMetals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bgMetals, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtComponentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComponentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComponentNameActionPerformed

    private void submitPhysicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPhysicalButtonActionPerformed
        bgMetals.setSelectedIndex(1);
    }//GEN-LAST:event_submitPhysicalButtonActionPerformed

    private void submitComponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitComponentButtonActionPerformed
        bgMetals.setSelectedIndex(1);
    }//GEN-LAST:event_submitComponentButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        int result =0;
        String output =null;
        
//        if(rd)
//        if(bgAcceptance.getElements().nextElement().isSelected()) {
//            bgAcceptance.getElements().nextElement().getText();
//           result += 3;  
//            System.out.println(bgAcceptance.getElements().nextElement().getText());
//        } else {
//            result +=-3;
//        }

if(rdAccFail.isSelected()) result -= 2;
if(rdAccPass.isSelected()) result += 2;
if(rdQualityFail.isSelected()) result -= 2;
if(rdQualityPass.isSelected()) result += 2;
if(rdProFail.isSelected()) result -= 2;
if(rdProtectPass.isSelected()) result += 2;
if(rdPerformFail.isSelected()) result -= 2;
if(rdPerformPass.isSelected()) result += 2;


if(rdFunctionalYes.isSelected()) result += 3;
if(rdFunctionalNo.isSelected()) result -= 3;
if(rdPhysicalYes.isSelected()) result += 3;
if(rdPhysicalNo.isSelected()) result -= 3;
if(rdAgeNo.isSelected()) result -= 3;
if(rdAgeYes.isSelected()) result += 3;
if(rdReYes.isSelected()) result += 3;
if(rdReNo.isSelected()) result -= 3;
if(rdXNo.isSelected()) result -= 3;
if(rdXYes.isSelected()) result += 3;


if(rdEnergyLow.isSelected()) result += 3;
if(rdEnergyHigh.isSelected()) result += 0 ;
if(rdEnergyVHigh.isSelected()) result -= 3;
if(rdExtractEase.isSelected()) result += 3;
if(rdExtractHard.isSelected()) result += 0;
if(rdExtractVhard.isSelected()) result -= 3;
if(rdLeadHigh.isSelected()) result += 0;
if(rdLeadLow.isSelected()) result += 3;
if(rdLeadVHigh.isSelected()) result -= 3;
if(rdPowerVHigh.isSelected()) result -= 3;
if(rdPowerHigh.isSelected()) result += 3;
if(rdToxicHigh.isSelected()) result += 0;
if(rdToxicLow.isSelected()) result += 3;
if(rdToxicVHigh.isSelected()) result -= 3;
        
        if(result >= 25 && result <= 40) {
            output ="Reused";
        } else if (result >= -10 && result <= 24) {
            output = "Extracted";
        } else {
            output ="Disposed";
        }
        
        JOptionPane.showMessageDialog(null,
        "Component should be "+ output,
        "A plain message",
        JOptionPane.PLAIN_MESSAGE);
            
    }//GEN-LAST:event_calcButtonActionPerformed

    private void rdFunctionalYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFunctionalYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFunctionalYesActionPerformed

    private void rdPhysicalYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPhysicalYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPhysicalYesActionPerformed

    private void rdToxicLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdToxicLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdToxicLowActionPerformed

    private void rdEnergyLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEnergyLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdEnergyLowActionPerformed

    private void rdExtractEaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdExtractEaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdExtractEaseActionPerformed

    private void rdExtractHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdExtractHardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdExtractHardActionPerformed

    private void rdExtractVhardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdExtractVhardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdExtractVhardActionPerformed

    private void rdLeadLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLeadLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLeadLowActionPerformed

    private void rdAccFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAccFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAccFailActionPerformed

    private void rdQualityFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdQualityFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdQualityFailActionPerformed

    private void rdProFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdProFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdProFailActionPerformed

    private void rdPerformFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPerformFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPerformFailActionPerformed

    private void rdPowerHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPowerHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPowerHighActionPerformed

    private void rdOutRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOutRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOutRangeActionPerformed

    private void rdRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdRangeActionPerformed

    private void rdPowerVHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPowerVHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPowerVHighActionPerformed

    private void rdHighCorrosion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHighCorrosion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdHighCorrosion1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Product product = workRequest.getProduct();

        if(((String)cmbAction.getSelectedItem()).equalsIgnoreCase("Working Fine")){
            network.getProductCatlog().getProductList().add(workRequest.getProduct());
            workRequest.setStatus(Constant.COMPLETE);
        }else if(((String)cmbAction.getSelectedItem()).equalsIgnoreCase("Send to Disposal")){
            workRequest.setStatus(Constant.COMPLETE);
            DisposalWorkRequest request = new DisposalWorkRequest();
            request.setProduct(product);
            request.setSender(userAccount);
            request.setStatus(Constant.SENT_TO_DISPOSER);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof DisposalOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                workRequest.setStatus(Constant.COMPLETE);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }else if(((String)cmbAction.getSelectedItem()).equalsIgnoreCase("Send for Extraction")){
            DisposalWorkRequest request = new DisposalWorkRequest();
            request.setProduct(product);
            request.setSender(userAccount);
            request.setStatus(Constant.SENT_TO_EXTRACTOR);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof ExtractionOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                workRequest.setStatus(Constant.COMPLETE);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }else if(((String)cmbAction.getSelectedItem()).equalsIgnoreCase("Send to third party for recycling")){
            DisposalWorkRequest request = new DisposalWorkRequest();
            request.setProduct(product);
            request.setSender(userAccount);
            request.setStatus(Constant.SENT_TO_THIRDPARTY);

            Organization org = null;
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList() ){
                if(enterprise instanceof OtherRecyclerEnterprise){
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof ReceiverOrganization){
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org!=null){
                workRequest.setStatus(Constant.COMPLETE);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rdLowPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLowPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLowPowerActionPerformed

    private void rdProtectPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdProtectPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdProtectPassActionPerformed

    private void rdLeadHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLeadHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLeadHighActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ageButtonGroup;
    private javax.swing.ButtonGroup bgAcceptance;
    private javax.swing.ButtonGroup bgAge;
    private javax.swing.ButtonGroup bgCapacitance;
    private javax.swing.ButtonGroup bgCorrosion;
    private javax.swing.ButtonGroup bgEnergy;
    private javax.swing.ButtonGroup bgEnergyUse;
    private javax.swing.ButtonGroup bgExtraction;
    private javax.swing.ButtonGroup bgLead;
    private javax.swing.JTabbedPane bgMetals;
    private javax.swing.ButtonGroup bgPerformance;
    private javax.swing.ButtonGroup bgPower;
    private javax.swing.ButtonGroup bgPrecious;
    private javax.swing.ButtonGroup bgProtection;
    private javax.swing.ButtonGroup bgQuality;
    private javax.swing.ButtonGroup bgToxic;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton calcButton;
    private javax.swing.JComboBox<String> cmbAction;
    private javax.swing.ButtonGroup functionalButtonGroup;
    private javax.swing.ButtonGroup internaButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblComponentName;
    private javax.swing.JLabel lblFunctional;
    private javax.swing.JLabel lblInternalDamage;
    private javax.swing.JLabel lblPhysicalYes;
    private javax.swing.JLabel lblPhysicalYes1;
    private javax.swing.JLabel lblPhysicalYes2;
    private javax.swing.ButtonGroup physicalButtonGroup;
    private javax.swing.JRadioButton rdAccFail;
    private javax.swing.JRadioButton rdAccPass;
    private javax.swing.JRadioButton rdAgeNo;
    private javax.swing.JRadioButton rdAgeYes;
    private javax.swing.JRadioButton rdEnergyHigh;
    private javax.swing.JRadioButton rdEnergyLow;
    private javax.swing.JRadioButton rdEnergyVHigh;
    private javax.swing.JRadioButton rdExtractEase;
    private javax.swing.JRadioButton rdExtractHard;
    private javax.swing.JRadioButton rdExtractVhard;
    private javax.swing.JRadioButton rdFunctionalNo;
    private javax.swing.JRadioButton rdFunctionalYes;
    private javax.swing.JRadioButton rdHighCorrosion;
    private javax.swing.JRadioButton rdHighCorrosion1;
    private javax.swing.JRadioButton rdLeadHigh;
    private javax.swing.JRadioButton rdLeadLow;
    private javax.swing.JRadioButton rdLeadVHigh;
    private javax.swing.JRadioButton rdLowPower;
    private javax.swing.JRadioButton rdOutRange;
    private javax.swing.JRadioButton rdPerformFail;
    private javax.swing.JRadioButton rdPerformPass;
    private javax.swing.JRadioButton rdPhysicalNo;
    private javax.swing.JRadioButton rdPhysicalYes;
    private javax.swing.JRadioButton rdPowerHigh;
    private javax.swing.JRadioButton rdPowerVHigh;
    private javax.swing.JRadioButton rdProFail;
    private javax.swing.JPanel rdProtectFail;
    private javax.swing.JRadioButton rdProtectPass;
    private javax.swing.JRadioButton rdQualityFail;
    private javax.swing.JRadioButton rdQualityPass;
    private javax.swing.JRadioButton rdRange;
    private javax.swing.JRadioButton rdReNo;
    private javax.swing.JRadioButton rdReYes;
    private javax.swing.JRadioButton rdToxicHigh;
    private javax.swing.JRadioButton rdToxicLow;
    private javax.swing.JRadioButton rdToxicVHigh;
    private javax.swing.JRadioButton rdVHighCorrosion;
    private javax.swing.JRadioButton rdVHighCorrosion1;
    private javax.swing.JRadioButton rdXNo;
    private javax.swing.JRadioButton rdXYes;
    private javax.swing.JRadioButton rdlowCorrosion;
    private javax.swing.JRadioButton rdlowCorrosion1;
    private javax.swing.JButton submitComponentButton;
    private javax.swing.JButton submitPhysicalButton;
    private javax.swing.JTextField txtComponentName;
    private javax.swing.ButtonGroup usedEarlierButtonGroup;
    // End of variables declaration//GEN-END:variables
}
