/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ewaste.ui.extraction;

import com.ewaste.business.enterprise.Enterprise;
import com.ewaste.business.enterprise.ManufacturerEnterprise;
import com.ewaste.business.enterprise.OtherRecyclerEnterprise;
import com.ewaste.business.helper.Constant;
import com.ewaste.business.network.Network;
import com.ewaste.business.organization.DisposalOrganization;
import com.ewaste.business.organization.Organization;
import com.ewaste.business.organization.ReceiverOrganization;
import com.ewaste.business.product.Product;
import com.ewaste.business.useraccount.UserAccount;
import com.ewaste.business.workqueue.DisposalWorkRequest;
import com.ewaste.business.workqueue.ManufacturerWorkRequest;
import com.ewaste.business.workqueue.ReceiverWorkRequest;
import com.ewaste.business.workqueue.WorkQueue;
import com.ewaste.business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jyotsna Khatter
 */
public class ExtractionResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form extractionWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;
    private WorkRequest workRequest;
    private static double nonFerrousTotal;

    public ExtractionResultPanel(JPanel userProcessContainer, WorkRequest workRequest, UserAccount userAccount, Network network, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.workRequest = workRequest;

        hideComponents();

        //selectListElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        extractionResultTabbedPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblPolyesters = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblPolypropylene = new javax.swing.JLabel();
        lblEpoxies = new javax.swing.JLabel();
        lblNylon = new javax.swing.JLabel();
        cmbPolypropylene = new javax.swing.JComboBox<>();
        cmbPolyesters = new javax.swing.JComboBox<>();
        cmbPolythylene = new javax.swing.JComboBox<>();
        cmbEpoxies = new javax.swing.JComboBox<>();
        cmbNylon = new javax.swing.JComboBox<>();
        lblQuantityPolyesters = new javax.swing.JLabel();
        lblQuantityPolypropylene = new javax.swing.JLabel();
        lblQuantityPolyethylene = new javax.swing.JLabel();
        lblQuantityEpoxies = new javax.swing.JLabel();
        lblQuantityNylon = new javax.swing.JLabel();
        txtFieldPolyesters = new javax.swing.JTextField();
        txtFieldPolypropylene = new javax.swing.JTextField();
        txtFieldEpoxies = new javax.swing.JTextField();
        txtFieldPolythylene = new javax.swing.JTextField();
        txtFieldNylon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnSendPolyesters = new javax.swing.JButton();
        cmbPolyestersSend = new javax.swing.JComboBox<>();
        btnSendPolypropylene = new javax.swing.JButton();
        cmbPolypropyleneSend = new javax.swing.JComboBox<>();
        btnSendPolyethylene = new javax.swing.JButton();
        cmbPolyethyleneSend = new javax.swing.JComboBox<>();
        btnSendEpoxies = new javax.swing.JButton();
        cmbEpoxiesSend = new javax.swing.JComboBox<>();
        btnSendNylon = new javax.swing.JButton();
        cmbNylonSend = new javax.swing.JComboBox<>();
        lblActionPolyesters = new javax.swing.JLabel();
        lblActionPolypropylene = new javax.swing.JLabel();
        lblActionEpoxies = new javax.swing.JLabel();
        lblPolyethylene = new javax.swing.JLabel();
        lblActionNylon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbAluminium = new javax.swing.JCheckBox();
        cbCopper = new javax.swing.JCheckBox();
        cbBrass = new javax.swing.JCheckBox();
        cbSteel = new javax.swing.JCheckBox();
        cbZinc = new javax.swing.JCheckBox();
        cbLead = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        txtFieldAluminium = new javax.swing.JTextField();
        lblQuantityLead = new javax.swing.JLabel();
        txtFieldZinc = new javax.swing.JTextField();
        lblQuantitySteel = new javax.swing.JLabel();
        lblQuantityCopper = new javax.swing.JLabel();
        txtFieldLead = new javax.swing.JTextField();
        lblQuantityAmuninum = new javax.swing.JLabel();
        lblQuantityBrass = new javax.swing.JLabel();
        txtFieldCopper = new javax.swing.JTextField();
        txtFieldSteel = new javax.swing.JTextField();
        lblQuantityZinc = new javax.swing.JLabel();
        txtFieldBrass = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        btnAdd1 = new javax.swing.JButton();
        btnAddAll1 = new javax.swing.JButton();
        btnRemove1 = new javax.swing.JButton();
        btnRemoveAll1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        btnSave = new javax.swing.JButton();
        btnCreateProduct = new javax.swing.JButton();
        lblMetalName = new javax.swing.JLabel();
        txtFieldMetalQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdYesHazardousWaste = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtFieldTotalWaste = new javax.swing.JTextField();
        btnSendToDisposal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel9.setText("jLabel6");

        jTextField4.setText("jTextField1");

        jLabel28.setText("Quantity:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Extraction Department");

        lblPolyesters.setText("Polyesters:");

        jLabel20.setText("Polyethylene:");

        lblPolypropylene.setText("Polypropylene");

        lblEpoxies.setText("Epoxies:");

        lblNylon.setText("Nylon:");

        cmbPolypropylene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "YES", "NO" }));
        cmbPolypropylene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPolypropyleneActionPerformed(evt);
            }
        });

        cmbPolyesters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "YES", "NO" }));
        cmbPolyesters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPolyestersActionPerformed(evt);
            }
        });

        cmbPolythylene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "YES", "NO" }));
        cmbPolythylene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPolythyleneActionPerformed(evt);
            }
        });

        cmbEpoxies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "YES", "NO" }));
        cmbEpoxies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEpoxiesActionPerformed(evt);
            }
        });

        cmbNylon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "YES", "NO" }));
        cmbNylon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNylonActionPerformed(evt);
            }
        });

        lblQuantityPolyesters.setText("Quantity:");

        lblQuantityPolypropylene.setText("Quantity:");

        lblQuantityPolyethylene.setText("Quantity:");

        lblQuantityEpoxies.setText("Quantity:");

        lblQuantityNylon.setText("Quantity:");

        jButton2.setText("Next >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel38.setText("Plastics");

        btnSendPolyesters.setText("Send");
        btnSendPolyesters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPolyestersActionPerformed(evt);
            }
        });

        cmbPolyestersSend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Recycler", "Manufacturer", "Third Recycler" }));

        btnSendPolypropylene.setText("Send");
        btnSendPolypropylene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPolypropyleneActionPerformed(evt);
            }
        });

        cmbPolypropyleneSend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Recycler", "Manufacturer", "Third Recycler" }));

        btnSendPolyethylene.setText("Send");
        btnSendPolyethylene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPolyethyleneActionPerformed(evt);
            }
        });

        cmbPolyethyleneSend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Recycler", "Manufacturer", "Third Recycler" }));

        btnSendEpoxies.setText("Send");
        btnSendEpoxies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEpoxiesActionPerformed(evt);
            }
        });

        cmbEpoxiesSend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Recycler", "Manufacturer", "Third Recycler" }));

        btnSendNylon.setText("Send");
        btnSendNylon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendNylonActionPerformed(evt);
            }
        });

        cmbNylonSend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Recycler", "Manufacturer", "Third Recycler" }));

        lblActionPolyesters.setText("Action:");

        lblActionPolypropylene.setText("Action:");

        lblActionEpoxies.setText("Action:");

        lblPolyethylene.setText("Action:");

        lblActionNylon.setText("Action:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblActionPolyesters))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblActionPolypropylene))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblActionEpoxies)))
                        .addComponent(lblPolyethylene, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblActionNylon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbNylonSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendNylon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbEpoxiesSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendEpoxies))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbPolypropyleneSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendPolypropylene))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbPolyethyleneSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendPolyethylene)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cmbPolyestersSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendPolyesters)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPolyestersSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActionPolyesters)
                    .addComponent(btnSendPolyesters))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendPolypropylene)
                    .addComponent(cmbPolypropyleneSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActionPolypropylene))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendPolyethylene)
                    .addComponent(cmbPolyethyleneSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolyethylene))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendEpoxies)
                    .addComponent(cmbEpoxiesSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActionEpoxies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNylonSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendNylon)
                    .addComponent(lblActionNylon))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPolypropylene, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPolyesters)
                                        .addComponent(lblEpoxies)
                                        .addComponent(jLabel20))
                                    .addComponent(lblNylon))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPolyesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPolypropylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPolythylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEpoxies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbNylon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantityPolyesters)
                                    .addComponent(lblQuantityPolypropylene)
                                    .addComponent(lblQuantityPolyethylene)
                                    .addComponent(lblQuantityEpoxies)
                                    .addComponent(lblQuantityNylon))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFieldNylon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldPolyesters, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldPolypropylene, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldPolythylene, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldEpoxies, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPolyesters)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbPolyesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblQuantityPolyesters)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPolypropylene)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbPolypropylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblQuantityPolypropylene))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFieldPolyesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtFieldPolypropylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbPolythylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantityPolyethylene)
                                    .addComponent(jLabel20))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEpoxies)
                                    .addComponent(cmbEpoxies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantityEpoxies)
                                    .addComponent(txtFieldEpoxies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNylon)
                                    .addComponent(cmbNylon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantityNylon)
                                    .addComponent(txtFieldNylon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtFieldPolythylene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        extractionResultTabbedPanel.addTab("MAGNETIC CURRENTS", jPanel2);

        jLabel31.setText("Non Ferrous Metals");

        jButton3.setText("Next >");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbAluminium.setText("Aluminium");
        cbAluminium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAluminiumActionPerformed(evt);
            }
        });

        cbCopper.setText("Copper");
        cbCopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCopperActionPerformed(evt);
            }
        });

        cbBrass.setText("Brass");
        cbBrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrassActionPerformed(evt);
            }
        });

        cbSteel.setText("Steel");
        cbSteel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSteelActionPerformed(evt);
            }
        });

        cbZinc.setText("Zinc");
        cbZinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZincActionPerformed(evt);
            }
        });

        cbLead.setText("Lead");
        cbLead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLeadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAluminium)
                    .addComponent(cbCopper)
                    .addComponent(cbBrass)
                    .addComponent(cbSteel)
                    .addComponent(cbZinc)
                    .addComponent(cbLead))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAluminium)
                .addGap(18, 18, 18)
                .addComponent(cbCopper)
                .addGap(27, 27, 27)
                .addComponent(cbBrass)
                .addGap(28, 28, 28)
                .addComponent(cbSteel)
                .addGap(18, 18, 18)
                .addComponent(cbZinc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cbLead)
                .addGap(22, 22, 22))
        );

        lblQuantityLead.setText("Quantity:");

        lblQuantitySteel.setText("Quantity:");

        lblQuantityCopper.setText("Quantity:");

        txtFieldLead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLeadActionPerformed(evt);
            }
        });

        lblQuantityAmuninum.setText("Quantity:");

        lblQuantityBrass.setText("Quantity:");

        txtFieldCopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCopperActionPerformed(evt);
            }
        });

        lblQuantityZinc.setText("Quantity:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(lblQuantityCopper)
                                    .addGap(11, 11, 11))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblQuantityAmuninum)
                                        .addComponent(lblQuantitySteel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantityZinc)
                                    .addComponent(lblQuantityLead))
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldLead)
                            .addComponent(txtFieldCopper)
                            .addComponent(txtFieldSteel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFieldBrass)
                            .addComponent(txtFieldZinc)
                            .addComponent(txtFieldAluminium, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblQuantityBrass, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityAmuninum)
                    .addComponent(txtFieldAluminium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityCopper)
                    .addComponent(txtFieldCopper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityBrass)
                    .addComponent(txtFieldBrass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantitySteel)
                    .addComponent(txtFieldSteel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityZinc)
                    .addComponent(txtFieldZinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityLead)
                    .addComponent(txtFieldLead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton6.setText("<Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addGap(172, 172, 172))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        extractionResultTabbedPanel.addTab("EDDY CURRENTS", jPanel3);

        list1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list1ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(list1);

        btnAdd1.setText("Add >");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnAddAll1.setText("Add all>");
        btnAddAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAll1ActionPerformed(evt);
            }
        });

        btnRemove1.setText("< Remove");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });

        btnRemoveAll1.setText("< Remove All");
        btnRemoveAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAll1ActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(list2);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCreateProduct.setText("Create Product");
        btnCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProductActionPerformed(evt);
            }
        });

        lblMetalName.setText("jLabel2");

        jButton1.setText("Next>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("< Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveAll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateProduct)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMetalName)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldMetalQuantity))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnSave)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnAdd1)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddAll1)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemove1)
                                .addGap(27, 27, 27)
                                .addComponent(btnRemoveAll1))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCreateProduct)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMetalName)
                            .addComponent(txtFieldMetalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(33, 33, 33))
        );

        extractionResultTabbedPanel.addTab("DENSITY SEPARATION", jPanel1);

        jLabel2.setText("Please indicate the residue obtained.");

        jLabel3.setText("Hazardous Plastics");

        buttonGroup1.add(rdYesHazardousWaste);
        rdYesHazardousWaste.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdYesHazardousWaste.setText("YES");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton2.setText("NO");

        jLabel4.setText("Mercury");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton3.setText("YES");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton4.setText("NO");

        jLabel5.setText("Beryllium");

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton5.setText("YES");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton6.setText("NO");

        jLabel6.setText("Cadmium");

        buttonGroup4.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton7.setText("YES");

        buttonGroup4.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton8.setText("NO");

        jLabel7.setText("Arsenic and Stibium");

        buttonGroup5.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton9.setText("YES");

        buttonGroup5.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton10.setText("NO");

        jLabel8.setText("CFCs, HCFCs,HFCs");

        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton11.setText("YES");

        buttonGroup6.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton12.setText("NO");

        jLabel10.setText("Total Waste");

        txtFieldTotalWaste.setText("jTextField1");

        btnSendToDisposal.setText("Send to Disposal >");
        btnSendToDisposal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToDisposalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdYesHazardousWaste)
                                .addComponent(jRadioButton3)
                                .addComponent(jRadioButton5)
                                .addComponent(jRadioButton7)
                                .addComponent(jRadioButton9)
                                .addComponent(jRadioButton11))
                            .addComponent(txtFieldTotalWaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton12)
                                    .addComponent(jRadioButton10)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton2)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                                .addComponent(btnSendToDisposal)))))
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdYesHazardousWaste)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton7)
                        .addComponent(jRadioButton8)))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton9)
                        .addComponent(jRadioButton10)))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFieldTotalWaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendToDisposal))
                .addGap(23, 23, 23))
        );

        extractionResultTabbedPanel.addTab("RESIDUE", jPanel6);

        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(extractionResultTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(extractionResultTabbedPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        validateMagneticCurrents();
        //extractionResultTabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbAluminiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAluminiumActionPerformed
        // TODO add your handling code here:
        if (cbAluminium.isSelected()) {
            lblQuantityAmuninum.setVisible(true);
            txtFieldAluminium.setVisible(true);
        } else {
            lblQuantityAmuninum.setVisible(false);
            txtFieldAluminium.setVisible(false);
        }

    }//GEN-LAST:event_cbAluminiumActionPerformed

    private void cbCopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCopperActionPerformed
        // TODO add your handling code here:
        if (cbCopper.isSelected()) {
            lblQuantityCopper.setVisible(true);
            txtFieldCopper.setVisible(true);
        } else {
            lblQuantityCopper.setVisible(false);
            txtFieldCopper.setVisible(false);
        }
    }//GEN-LAST:event_cbCopperActionPerformed

    private void cbBrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrassActionPerformed
        // TODO add your handling code here:
        if (cbBrass.isSelected()) {
            lblQuantityBrass.setVisible(true);
            txtFieldBrass.setVisible(true);
        } else {
            lblQuantityBrass.setVisible(false);
            txtFieldBrass.setVisible(false);
        }
    }//GEN-LAST:event_cbBrassActionPerformed

    private void cbSteelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSteelActionPerformed
        // TODO add your handling code here:
        if (cbSteel.isSelected()) {
            lblQuantitySteel.setVisible(true);
            txtFieldSteel.setVisible(true);
        } else {
            lblQuantitySteel.setVisible(false);
            txtFieldSteel.setVisible(false);
        }
    }//GEN-LAST:event_cbSteelActionPerformed

    private void txtFieldLeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLeadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLeadActionPerformed

    private void cbZincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbZincActionPerformed
        // TODO add your handling code here:
        if (cbZinc.isSelected()) {
            lblQuantityZinc.setVisible(true);
            txtFieldZinc.setVisible(true);
        } else {
            lblQuantityZinc.setVisible(false);
            txtFieldZinc.setVisible(false);
        }
    }//GEN-LAST:event_cbZincActionPerformed

    private void cbLeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLeadActionPerformed
        // TODO add your handling code here:
        if (cbLead.isSelected()) {
            lblQuantityLead.setVisible(true);
            txtFieldLead.setVisible(true);
        } else {
            lblQuantityLead.setVisible(false);
            txtFieldLead.setVisible(false);
        }
    }//GEN-LAST:event_cbLeadActionPerformed

    private void cmbPolyestersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPolyestersActionPerformed
        // TODO add your handling code here:
        String polyesters = cmbPolyesters.getSelectedItem().toString();

        if (polyesters.equalsIgnoreCase("yes")) {

            lblQuantityPolyesters.setVisible(true);
            txtFieldPolyesters.setVisible(true);
            cmbPolyestersSend.setVisible(true);
            btnSendPolyesters.setVisible(true);
            lblActionPolyesters.setVisible(true);
        } else {
            lblQuantityPolyesters.setVisible(false);
            txtFieldPolyesters.setVisible(false);
            cmbPolyestersSend.setVisible(false);
            btnSendPolyesters.setVisible(false);
            lblActionPolyesters.setVisible(false);
        }

    }//GEN-LAST:event_cmbPolyestersActionPerformed

    private void cmbPolypropyleneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPolypropyleneActionPerformed
        // TODO add your handling code here:
        String polypropylene = cmbPolypropylene.getSelectedItem().toString();

        if (polypropylene.equalsIgnoreCase("yes")) {

            lblQuantityPolypropylene.setVisible(true);
            txtFieldPolypropylene.setVisible(true);
            cmbPolypropyleneSend.setVisible(true);
            btnSendPolypropylene.setVisible(true);
            lblActionPolypropylene.setVisible(true);
        } else {
            lblQuantityPolypropylene.setVisible(false);
            txtFieldPolypropylene.setVisible(false);
            cmbPolypropyleneSend.setVisible(false);
            btnSendPolypropylene.setVisible(false);
            lblActionPolypropylene.setVisible(false);
        }
    }//GEN-LAST:event_cmbPolypropyleneActionPerformed

    private void cmbPolythyleneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPolythyleneActionPerformed
        // TODO add your handling code here:
        String polythylene = cmbPolythylene.getSelectedItem().toString();

        if (polythylene.equalsIgnoreCase("yes")) {

            lblQuantityPolyethylene.setVisible(true);
            txtFieldPolythylene.setVisible(true);
            cmbPolyethyleneSend.setVisible(true);
            btnSendPolyethylene.setVisible(true);
            lblPolyethylene.setVisible(true);

        } else {
            lblQuantityPolyethylene.setVisible(false);
            txtFieldPolythylene.setVisible(false);
            cmbPolyethyleneSend.setVisible(false);
            btnSendPolyethylene.setVisible(false);
            lblPolyethylene.setVisible(false);
        }

    }//GEN-LAST:event_cmbPolythyleneActionPerformed

    private void cmbEpoxiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEpoxiesActionPerformed
        // TODO add your handling code here:
        String epoxies = cmbEpoxies.getSelectedItem().toString();

        if (epoxies.equalsIgnoreCase("yes")) {

            lblQuantityEpoxies.setVisible(true);
            txtFieldEpoxies.setVisible(true);
            cmbEpoxiesSend.setVisible(true);
            btnSendEpoxies.setVisible(true);
            lblActionEpoxies.setVisible(true);
        } else {
            lblQuantityEpoxies.setVisible(false);
            txtFieldEpoxies.setVisible(false);
            cmbEpoxiesSend.setVisible(false);
            btnSendEpoxies.setVisible(false);
            lblActionEpoxies.setVisible(false);
        }
    }//GEN-LAST:event_cmbEpoxiesActionPerformed

    private void cmbNylonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNylonActionPerformed
        // TODO add your handling code here:
        String nylon = cmbNylon.getSelectedItem().toString();

        if (nylon.equalsIgnoreCase("yes")) {

            lblQuantityNylon.setVisible(true);
            txtFieldNylon.setVisible(true);
            cmbNylonSend.setVisible(true);
            btnSendNylon.setVisible(true);
            lblActionNylon.setVisible(true);
        } else {
            lblQuantityNylon.setVisible(false);
            txtFieldNylon.setVisible(false);
            cmbNylonSend.setVisible(false);
            btnSendNylon.setVisible(false);
            lblActionNylon.setVisible(false);
        }
    }//GEN-LAST:event_cmbNylonActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //extractionResultTabbedPanel.setSelectedIndex(1);
        validateEddyCurrents();
        //loadMetals();
    }//GEN-LAST:event_jButton3ActionPerformed

    DefaultListModel dlm = new DefaultListModel();

    public void loadMetals() {
        for (int i = 0; i < 10; i++) {
            dlm.addElement("item " + i);
        }
        list1.setModel(dlm);
    }

    DefaultListModel dlm2 = new DefaultListModel();
    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        for (String s : list1.getSelectedValuesList()) {
            dlm2.addElement(s);
            dlm.remove(list1.getSelectedIndex());
            list2.setModel(dlm2);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAddAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAll1ActionPerformed
        // TODO add your handling code here:
        int start = 0;
        int end = list1.getModel().getSize() - 1;
        if (end >= 0) {
            list1.setSelectionInterval(start, end);
        }
        for (String s : list1.getSelectedValuesList()) {
            dlm2.addElement(s);
            dlm.remove(list1.getSelectedIndex());
            list2.setModel(dlm2);
        }
    }//GEN-LAST:event_btnAddAll1ActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        for (String s : list2.getSelectedValuesList()) {
            dlm.addElement(s);
            dlm2.remove(list2.getSelectedIndex());
            list1.setModel(dlm);
        }
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void btnRemoveAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAll1ActionPerformed
        // TODO add your handling code here:
        int start = 0;
        int end = list2.getModel().getSize() - 1;
        if (end >= 0) {
            list2.setSelectionInterval(start, end);
        }

        for (String s : list2.getSelectedValuesList()) {
            dlm.addElement(s);
            dlm2.remove(list2.getSelectedIndex());
            list1.setModel(dlm);
        }
    }//GEN-LAST:event_btnRemoveAll1ActionPerformed

    private void list1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ValueChanged

    private void btnCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProductActionPerformed
        // TODO add your handling code here:
        lblMetalName.setVisible(true);
        txtFieldMetalQuantity.setVisible(true);
        lblMetalName.setText(list2.getSelectedValue());
    }//GEN-LAST:event_btnCreateProductActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Product product = network.getProductCatlog().addNewProduct();
        product.setProductName(lblMetalName.getText());
        product.setQuantity(Double.parseDouble(txtFieldMetalQuantity.getText()));
        lblMetalName.setText("Metal Name");
        lblMetalName.setVisible(false);
        txtFieldMetalQuantity.setText("");
        txtFieldMetalQuantity.setVisible(false);
        dlm2.remove(list2.getSelectedIndex());
        JOptionPane.showMessageDialog(this, "Product created successfully");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFieldCopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCopperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCopperActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (dlm2.getSize() == 0) {
            extractionResultTabbedPanel.setSelectedIndex(2);
        } else {
            JOptionPane.showMessageDialog(this, "Ensure all products are created!");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSendPolyestersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPolyestersActionPerformed
        // TODO add your handling code here:
        if (txtFieldPolyesters.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity");
            return;
        } else {
            String name = lblPolyesters.getText();
            double quantity = Double.parseDouble(txtFieldPolyesters.getText());
            if (cmbPolyestersSend.getSelectedIndex() == 1) {
                sendToApporprateReceiver(1,name,quantity);
            }else if (cmbPolyestersSend.getSelectedIndex() == 2) {
                sendToApporprateReceiver(2,name,quantity);
            }else{
                sendToApporprateReceiver(0,name,quantity);
            }
            
        }
    }//GEN-LAST:event_btnSendPolyestersActionPerformed

    private void sendToApporprateReceiver(int receiver,String name, double quantity){
        Product product = new Product();
            product.setProductName(name);
            product.setQuantity(quantity);
            if (receiver == 1) {
                workRequest.setStatus(Constant.COMPLETE);
                ReceiverWorkRequest request = new ReceiverWorkRequest();
                request.setProduct(product);
                request.setSender(userAccount);
                request.setStatus(Constant.SENT_TO_MANUFACTURER);

                Organization org = null;
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof ManufacturerEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof ReceiverOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }
                }
                if (org != null) {
                    workRequest.setStatus(Constant.COMPLETE);
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                    
                }
            } else if (receiver == 2) {
                workRequest.setStatus(Constant.COMPLETE);
                ReceiverWorkRequest request = new ReceiverWorkRequest();
                request.setProduct(product);
                request.setSender(userAccount);
                request.setStatus(Constant.SENT_TO_THIRDPARTY);

                Organization org = null;
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof OtherRecyclerEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof ReceiverOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }
                }
                if (org != null) {
                    workRequest.setStatus(Constant.COMPLETE);
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
            } else {
                network.getProductCatlog().getProductList().add(product);
                workRequest.setStatus(Constant.COMPLETE);
            }
    }
    
    private void btnSendPolypropyleneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPolypropyleneActionPerformed
        // TODO add your handling code here:
        if (txtFieldPolypropylene.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity");
            return;
        } else {
            String name = lblPolypropylene.getText();
            double quantity = Double.parseDouble(txtFieldPolypropylene.getText());
            if (cmbPolypropyleneSend.getSelectedIndex() == 1) {
                sendToApporprateReceiver(1,name,quantity);
            }else if (cmbPolypropyleneSend.getSelectedIndex() == 2) {
                sendToApporprateReceiver(2,name,quantity);
            }else{
                sendToApporprateReceiver(0,name,quantity);
            }
            
        }
    }//GEN-LAST:event_btnSendPolypropyleneActionPerformed

    private void btnSendPolyethyleneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPolyethyleneActionPerformed
        // TODO add your handling code here:
        if (txtFieldPolythylene.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity");
            return;
        } else {
            String name = lblPolyethylene.getText();
            double quantity = Double.parseDouble(txtFieldPolythylene.getText());
            if (cmbPolyethyleneSend.getSelectedIndex() == 1) {
                sendToApporprateReceiver(1,name,quantity);
            }else if (cmbPolyethyleneSend.getSelectedIndex() == 2) {
                sendToApporprateReceiver(2,name,quantity);
            }else{
                sendToApporprateReceiver(0,name,quantity);
            }
            
        }
    }//GEN-LAST:event_btnSendPolyethyleneActionPerformed

    private void btnSendEpoxiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEpoxiesActionPerformed
        // TODO add your handling code here:
        if (txtFieldEpoxies.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity");
            return;
        } else {
            String name = lblEpoxies.getText();
            double quantity = Double.parseDouble(txtFieldEpoxies.getText());
            if (cmbEpoxiesSend.getSelectedIndex() == 1) {
                sendToApporprateReceiver(1,name,quantity);
            }else if (cmbEpoxiesSend.getSelectedIndex() == 2) {
                sendToApporprateReceiver(2,name,quantity);
            }else{
                sendToApporprateReceiver(0,name,quantity);
            }
            
        }
    }//GEN-LAST:event_btnSendEpoxiesActionPerformed

    private void btnSendNylonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendNylonActionPerformed
        // TODO add your handling code here:
        if (txtFieldNylon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity");
            return;
        } else {
            String name = lblNylon.getText();
            double quantity = Double.parseDouble(txtFieldNylon.getText());
            if (cmbNylonSend.getSelectedIndex() == 1) {
                sendToApporprateReceiver(1,name,quantity);
            }else if (cmbNylonSend.getSelectedIndex() == 2) {
                sendToApporprateReceiver(2,name,quantity);
            }else{
                sendToApporprateReceiver(0,name,quantity);
            }
            
        }
    }//GEN-LAST:event_btnSendNylonActionPerformed

    private void btnSendToDisposalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToDisposalActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        if (!txtFieldTotalWaste.getText().trim().isEmpty()) {
            workRequest.setStatus(Constant.COMPLETE);
            DisposalWorkRequest request = new DisposalWorkRequest();
            request.setProduct(product);
            request.setSender(userAccount);
            request.setStatus(Constant.SENT_TO_DISPOSER);
            request.getProduct().setProductName("Hazardous Metals");

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof DisposalOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                workRequest.setStatus(Constant.COMPLETE);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(this, "Residue sent to disposer successfully!");

                //set all componets to visisble false
                //calculate waste function
            }
        }
    }//GEN-LAST:event_btnSendToDisposalActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        extractionResultTabbedPanel.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        extractionResultTabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    public void hideComponents() {
        lblQuantityAmuninum.setVisible(false);
        lblQuantityBrass.setVisible(false);
        lblQuantityCopper.setVisible(false);
        lblQuantityLead.setVisible(false);
        lblQuantitySteel.setVisible(false);
        lblQuantityZinc.setVisible(false);
        lblQuantityPolyesters.setVisible(false);
        lblQuantityPolyethylene.setVisible(false);
        lblQuantityPolypropylene.setVisible(false);
        lblQuantityEpoxies.setVisible(false);
        lblQuantityNylon.setVisible(false);
        lblMetalName.setVisible(false);
        lblActionEpoxies.setVisible(false);
        lblActionNylon.setVisible(false);
        lblActionPolyesters.setVisible(false);
        lblActionPolypropylene.setVisible(false);
        lblPolyethylene.setVisible(false);
//        lblPd.setVisible(false);
//        lblPt.setVisible(false);
//        lblRh.setVisible(false);
//        lblSe.setVisible(false);
//        lblTe.setVisible(false);
//        

        txtFieldAluminium.setVisible(false);
        txtFieldBrass.setVisible(false);
        txtFieldCopper.setVisible(false);
        txtFieldLead.setVisible(false);
        txtFieldSteel.setVisible(false);
        txtFieldZinc.setVisible(false);
        txtFieldPolyesters.setVisible(false);
        txtFieldPolypropylene.setVisible(false);
        txtFieldPolythylene.setVisible(false);
        txtFieldEpoxies.setVisible(false);
        txtFieldNylon.setVisible(false);
        txtFieldMetalQuantity.setVisible(false);
//        txtFieldAu.setVisible(false);
//        txtFieldBe.setVisible(false);
//        txtFieldHg.setVisible(false);
//        txtFieldPd.setVisible(false);
//        txtFieldPt.setVisible(false);
//        txtFieldRh.setVisible(false);
//        txtFieldIn.setVisible(false);
//        txtFieldGa.setVisible(false);
//        txtFieldTe.setVisible(false);
//        txtFieldSe.setVisible(false);
//        
        btnSendEpoxies.setVisible(false);
        btnSendPolyesters.setVisible(false);
        btnSendPolyethylene.setVisible(false);
        btnSendPolypropylene.setVisible(false);
        btnSendNylon.setVisible(false);

        cmbEpoxiesSend.setVisible(false);
        cmbNylonSend.setVisible(false);
        cmbPolyestersSend.setVisible(false);
        cmbPolyethyleneSend.setVisible(false);
        cmbPolypropyleneSend.setVisible(false);

    }

    public void validateMagneticCurrents() {
        boolean test, a, b, c, d, e;
        if (txtFieldPolyesters.isVisible() && txtFieldAluminium.getText().equals("")) {
            a = true;
        } else {
            a = false;
            //btnSendPolyesters.setEnabled(true);
        }
        if (txtFieldPolythylene.isVisible() && txtFieldPolythylene.getText().trim().isEmpty()) {
            b = true;
        } else {
            b = false;
            //btnSendPolyethylene.setEnabled(true);
        }

        if (txtFieldPolypropylene.isVisible() && txtFieldPolypropylene.getText().trim().isEmpty()) {
            c = true;
        } else {
            c = false;
            //btnSendPolypropylene.setEnabled(true);
        }

        if (txtFieldEpoxies.isVisible() && txtFieldEpoxies.getText().trim().isEmpty()) {
            d = true;
        } else {
            d = false;
            //btnSendEpoxies.setEnabled(true);
        }

        if (txtFieldNylon.isVisible() && txtFieldNylon.getText().trim().isEmpty()) {
            e = true;
        } else {
            e = false;
            //btnSendNylon.setEnabled(true);
        }

        test = a || b || c || d || e;
        if (test) {
            JOptionPane.showMessageDialog(null, "Enter all the fields!");
            return;
        } else {
            extractionResultTabbedPanel.setSelectedIndex(1);
        }

    }

    public void validateEddyCurrents() {
        boolean a = txtFieldAluminium.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();
        boolean b = txtFieldBrass.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();
        boolean c = txtFieldCopper.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();
        boolean d = txtFieldLead.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();
        boolean e = txtFieldZinc.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();
        boolean f = txtFieldSteel.isEnabled() && txtFieldAluminium.getText().trim().isEmpty();

        boolean test = a || b || c || d || e || f;

        if (false != test) {
            JOptionPane.showMessageDialog(null, "Enter all the fields!");
            return;
        } else {
            double total = calcNonFerrousTotal();
            //how to get current product??????????????
            workRequest.getProduct().setNonFerrousMetals(total);
            loadMetals();
            extractionResultTabbedPanel.setSelectedIndex(2);
        }
    }

    public double calcNonFerrousTotal() {

        if (!txtFieldAluminium.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldAluminium.getText());
        } else {

        }

        if (!txtFieldBrass.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldBrass.getText());
        } else {

        }
        if (!txtFieldCopper.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldCopper.getText());
        } else {

        }
        if (!txtFieldLead.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldLead.getText());
        } else {

        }
        if (!txtFieldSteel.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldSteel.getText());
        } else {

        }
        if (!txtFieldZinc.getText().trim().isEmpty()) {
            nonFerrousTotal = nonFerrousTotal + Double.parseDouble(txtFieldZinc.getText());
        } else {

        }
        return nonFerrousTotal;
    }

//    public void selectListElements(){
//        
//        DefaultListModel dlm = (DefaultListModel)listPGE.getModel();
//        //DefaultListModel dlm = new DefaultListModel();
//        ListSelectionModel lsm = (ListSelectionModel) listPGE.getModel();
//        listPGE.setModel(dlm);
//        listPGE.getSelectionModel().addListSelectionListener(e -> {
//            if(listPGE.isSelectedIndex(0)){
//           lblPd.setVisible(true);
//           txtFieldPd.setVisible(true);
//       }
//        });
//       
//       
//       if(listPGE.isSelectedIndex(1)){
//           lblPt.setVisible(true);
//           txtFieldPt.setVisible(true);
//       }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddAll1;
    private javax.swing.JButton btnCreateProduct;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnRemoveAll1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSendEpoxies;
    private javax.swing.JButton btnSendNylon;
    private javax.swing.JButton btnSendPolyesters;
    private javax.swing.JButton btnSendPolyethylene;
    private javax.swing.JButton btnSendPolypropylene;
    private javax.swing.JButton btnSendToDisposal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox cbAluminium;
    private javax.swing.JCheckBox cbBrass;
    private javax.swing.JCheckBox cbCopper;
    private javax.swing.JCheckBox cbLead;
    private javax.swing.JCheckBox cbSteel;
    private javax.swing.JCheckBox cbZinc;
    private javax.swing.JComboBox<String> cmbEpoxies;
    private javax.swing.JComboBox<String> cmbEpoxiesSend;
    private javax.swing.JComboBox<String> cmbNylon;
    private javax.swing.JComboBox<String> cmbNylonSend;
    private javax.swing.JComboBox<String> cmbPolyesters;
    private javax.swing.JComboBox<String> cmbPolyestersSend;
    private javax.swing.JComboBox<String> cmbPolyethyleneSend;
    private javax.swing.JComboBox<String> cmbPolypropylene;
    private javax.swing.JComboBox<String> cmbPolypropyleneSend;
    private javax.swing.JComboBox<String> cmbPolythylene;
    private javax.swing.JTabbedPane extractionResultTabbedPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblActionEpoxies;
    private javax.swing.JLabel lblActionNylon;
    private javax.swing.JLabel lblActionPolyesters;
    private javax.swing.JLabel lblActionPolypropylene;
    private javax.swing.JLabel lblEpoxies;
    private javax.swing.JLabel lblMetalName;
    private javax.swing.JLabel lblNylon;
    private javax.swing.JLabel lblPolyesters;
    private javax.swing.JLabel lblPolyethylene;
    private javax.swing.JLabel lblPolypropylene;
    private javax.swing.JLabel lblQuantityAmuninum;
    private javax.swing.JLabel lblQuantityBrass;
    private javax.swing.JLabel lblQuantityCopper;
    private javax.swing.JLabel lblQuantityEpoxies;
    private javax.swing.JLabel lblQuantityLead;
    private javax.swing.JLabel lblQuantityNylon;
    private javax.swing.JLabel lblQuantityPolyesters;
    private javax.swing.JLabel lblQuantityPolyethylene;
    private javax.swing.JLabel lblQuantityPolypropylene;
    private javax.swing.JLabel lblQuantitySteel;
    private javax.swing.JLabel lblQuantityZinc;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JRadioButton rdYesHazardousWaste;
    private javax.swing.JTextField txtFieldAluminium;
    private javax.swing.JTextField txtFieldBrass;
    private javax.swing.JTextField txtFieldCopper;
    private javax.swing.JTextField txtFieldEpoxies;
    private javax.swing.JTextField txtFieldLead;
    private javax.swing.JTextField txtFieldMetalQuantity;
    private javax.swing.JTextField txtFieldNylon;
    private javax.swing.JTextField txtFieldPolyesters;
    private javax.swing.JTextField txtFieldPolypropylene;
    private javax.swing.JTextField txtFieldPolythylene;
    private javax.swing.JTextField txtFieldSteel;
    private javax.swing.JTextField txtFieldTotalWaste;
    private javax.swing.JTextField txtFieldZinc;
    // End of variables declaration//GEN-END:variables
}
